<?php

/**
 * @file
 * Image effect to automatically crop images.
 */

/**
 * Implements hook_image_effect_info().
 */
function imagecache_autocrop_image_effect_info() {
  $effects = array();

  $effects['imagecache_autocrop'] = array(
    'label' => t('Autocrop'),
    'help' => t('Crop image based on selected color.'),
    'effect callback' => 'imagecache_autocrop_image',
    'form callback' => 'imagecache_autocrop_form',
  );

  return $effects;
}

/**
 * Settings form callback.
 */
function imagecache_autocrop_form($action) {
  $form = array();

  $defaults = array(
    'tolerance' => 5,
    'grid' => 1,
  );

  $action = array_merge($defaults, (array) $action);

  $form['tolerance'] = array(
    '#type' => 'textfield',
    '#title' => t('Tolerance'),
    '#default_value' => $action['tolerance'],
    '#size' => 5,
    '#required' => TRUE,
    '#description' => t('Acceptable deviation from background color. Values are from 0 (black) to 255 (white).'),
    '#element_validate' => array('imagecache_autocrop_tolerance_validate'),
  );

  $form['grid'] = array(
    '#type' => 'select',
    '#title' => t('Grid size'),
    '#default_value' => $action['grid'],
    '#options' => array_combine(range(1, 32), range(1, 32)),
    '#required' => TRUE,
    '#description' => t('Pixel grid size, from 1 to 32. Values higher than 1 are n<sup>2</sup> times faster, but may miss fine detail and will not crop as tight.'),
    '#element_validate' => array('imagecache_autocrop_grid_validate'),
  );

  return $form;
}

/**
 * Validation callback for tolerance value.
 */
function imagecache_autocrop_tolerance_validate($element, &$form_state, $form) {
  if (!is_numeric($element['#value']) || (int) $element['#value'] < 0 || $element['#value'] > 255) {
    form_error($element, t('The value should be a number between 0 and 255.'));
  }
}

/**
 * Validation callback for grid value.
 */
function imagecache_autocrop_grid_validate($element, &$form_state, $form) {
  if (!is_numeric($element['#value']) || (int) $element['#value'] < 1 || $element['#value'] > 32) {
    form_error($element, t('The value should be a number between 1 and 32.'));
  }
}

/**
 * Image processing callback.
 *
 * @param object $image
 *   Image object.
 * @param array $data
 *   Values from the settings form.
 */
function imagecache_autocrop_image(&$image, $data) {
  // Get image resource.
  if (image_gd_load($image)) {
    $dimensions = _image_autocrop_get_edges($image->resource, $data['tolerance'], $data['grid']);
    $data = array(
      'width' => $dimensions['right'] - $dimensions['left'],
      'height' => $dimensions['bottom'] - $dimensions['top'],
      'anchor' => $dimensions['left'] . '-' . $dimensions['top'],
    );

    // Apply crop based on dimensions, but only if the tolerance value was not
    // too large and the whole image was cropped out.
    if ($data['width'] > 0 && $data['height'] > 0) {
      image_crop_effect($image, $data);
    }
  }
}

/**
 * Get edges of wanted pixels for an image.
 *
 * @param resource $image_resource
 *   Image resource.
 * @param int $tolerance
 *   Acceptable range +- from colour. 0-255. Defaults to 5.
 * @param int $grid
 *   Pixel grid processing size. 1-32. Defaults to 1.
 * @param int $color
 *   Color to be 'trimmed'.  Allowable range 0 (black) to 255 (white).  If null
 *   (or outside 0 - 255) will use top/left corner color as default.
 *
 * @return array
 *   Associative array of wanted pixels (top, right, bottom, left)
 *
 * @see http://www.php.net/manual/en/function.imagecolorat.php#107970
 */
function _image_autocrop_get_edges($image_resource, $tolerance = 5, $grid = 1, $color = NULL) {
  // If trim colour ($c) isn't a number between 0 - 255.
  if (!is_numeric($color) || $color < 0 || $color > 255) {
    // Grab the colour from the top left corner and use that as default.
    // 2 pixels in to avoid messy edges.
    $rgb = imagecolorat($image_resource, 2, 2);
    $r = ($rgb >> 16) & 0xFF;
    $g = ($rgb >> 8) & 0xFF;
    $b = $rgb & 0xFF;
    // Average of rgb is good enough for a default.
    $color = round(($r + $g + $b) / 3);
  }

  // If tolerance isn't a number between 0 - 255 use 10 as default.
  if (!is_numeric($tolerance) || $tolerance < 0 || $tolerance > 255) {
    $tolerance = 10;
  }

  // If grid isn't a number between 1 - 32 use 1 as default.
  if (!is_numeric($grid) || $grid < 1 || $grid > 32) {
    $grid = 1;
  }

  $min = $color - $tolerance;
  $max = $color + $tolerance;

  $w = imagesx($image_resource);
  $h = imagesy($image_resource);

  $y_axis = array();
  $x_axis = array();
  for ($x = 0; $x < $w; $x = $x + $grid) {
    for ($y = 0; $y < $h; $y = $y + $grid) {
      $rgb = imagecolorat($image_resource, $x, $y);
      $r = ($rgb >> 16) & 0xFF;
      $g = ($rgb >> 8) & 0xFF;
      $b = $rgb & 0xFF;
      if (
        ($r < $min || $r > $max) &&
        ($g < $min || $g > $max) &&
        ($b < $min || $b > $max)
      ) {
        // Using x and y as keys condenses all rows and all columns
        // into just one X array and one Y array.
        // However, the keys are treated as literal and therefore are not in
        // numeric order, so we need to sort them in order to get the first
        // and last X and Y occurrences of wanted pixels.
        // Normal sorting will remove keys so we also use x and y as values,
        // this way they are still available without preserving keys.
        $y_axis[$y] = $y;
        $x_axis[$x] = $x;
        // Note: $y_axis[] = $y; and $x_axis[] = $x; works just as well
        // but results in much much larger arrays than is necessary
        // array_unique would reduce size again but this method is quicker.
      }
    }
  }
  // Sort them so first and last occurrences are at start and end.
  sort($y_axis);
  sort($x_axis);

  // Find crop bounds and add a margin to allow for the grid size.
  $margin = $grid - 1;
  $top = array_shift($y_axis) - $margin;
  $right = array_pop($x_axis) + $margin;
  $bottom = array_pop($y_axis) + $margin;
  $left = array_shift($x_axis) - $margin;

  // Check crop bounds are not outside the image dimensions.
  return array(
    'top' => $top < 0 ? 0 : $top,
    'right' => $right > $w ? $w : $right,
    'bottom' => $bottom > $h ? $h : $bottom,
    'left' => $left < 0 ? 0 : $left,
  );
}
